### ISSUE TITLE
XQ32s from Professor Layton vs. Phoenix Wright - Ace Attorney cannot be extracted

### ISSUE THREAD

**Issue by in1tiate** [onepiecefreak3/XtractQuery#2] opened 2021-04-30 02:55 UTC
Some sample files:
[XQ32-PLvsPWAA.zip](https://github.com/onepiecefreak3/XtractQuery/files/6402761/XQ32-PLvsPWAA.zip)

Output:
```
>XtractQuery.exe -o e -t xq32 -f 10_100110.xq
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at XtractQuery.Parsers.StringReader.HashStrings()
   at XtractQuery.Parsers.StringReader..ctor(Stream input)
   at XtractQuery.Parsers.Xq32Parser.CreateStringReader(BinaryReaderX br, Xq32Header header)
   at XtractQuery.Parsers.Xq32Parser.ParseTables(Stream input, Int32& headerUnk)
   at XtractQuery.Parsers.Xq32Parser.Decompile(Stream input, Stream output)
   at XtractQuery.Program.ExtractFile(String type, String file)
   at XtractQuery.Program.Main(String[] args)
```

I'm not very knowledgeable about this format, but the contents seem to be in barely obfuscated plain text? At least, I can read some of it (though there's bits of garbage placed within)

**Comment by in1tiate** [comment] 2021-04-30 03:06
Small correction - this applies merely to *most* XQ32 files in PLvsPW-AA. I found two XQ32 files that worked while investigating:
[WorkingXQ32.zip](https://github.com/onepiecefreak3/XtractQuery/files/6402786/WorkingXQ32.zip)
and one that gave me an error I hadn't seen before:
[02_020025.zip](https://github.com/onepiecefreak3/XtractQuery/files/6402787/02_020025.zip)
```
>XtractQuery.exe -o e -t xq32 -f 02_020025.xq
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt16()
   at Komponent.IO.BinaryReaderX.ReadInt16()
   at Komponent.IO.BinarySupport.TypeReader.ReadTypePrimitive(BinaryReaderX br, Type readType)
   at Komponent.IO.BinarySupport.TypeReader.ReadTypeInternal(BinaryReaderX br, Type readType, ValueStorage storage, FieldInfo fieldInfo, Boolean isTypeChose)
   at Komponent.IO.BinarySupport.TypeReader.ReadTypeClass(BinaryReaderX br, Type readType, ValueStorage storage)
   at Komponent.IO.BinarySupport.TypeReader.ReadTypeInternal(BinaryReaderX br, Type readType, ValueStorage storage, FieldInfo fieldInfo, Boolean isTypeChose)
   at Komponent.IO.BinarySupport.TypeReader.ReadType(BinaryReaderX br, Type readType)
   at Komponent.IO.BinaryReaderX.ReadType[T]()
   at Komponent.IO.BinaryReaderX.<ReadMultiple>b__63_0[T](Int32 _)
   at System.Linq.Enumerable.SelectRangeIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Komponent.IO.BinaryReaderX.ReadMultiple[T](Int32 count)
   at XtractQuery.Parsers.Xq32Parser.ParseFunctions(BinaryReaderX br, Xq32Header header, IList`1 jumps, IList`1 instructions)
   at XtractQuery.Parsers.Xq32Parser.ParseTables(Stream input, Int32& headerUnk)
   at XtractQuery.Parsers.Xq32Parser.Decompile(Stream input, Stream output)
   at XtractQuery.Program.ExtractFile(String type, String file)
   at XtractQuery.Program.Main(String[] args)
```

**Comment by onepiecefreak3** [comment] 2021-04-30 06:59
XQ32 is not plain text. It's a complex compiled script of functions, which is why this tool exists to begin with. I will investigate the errors as soon as I'm able to.

**Comment by onepiecefreak3** [comment] 2021-07-21 21:09
Finally got around investigating this issue.
It could not be reproduced in any capacity. Given all the samples in this issue and using the commands specified, all XQ32 sample files could be extracted without a problem using the newest release from April 17th (so the release 13 days before this issue was created).

The EndOfStreamException issue comes up, because I assume you use the same command as in the OP, however, the given script for that problem is an XSEQ. So -t xseq has to be specified. I will add an automatic detection when extracting a script, so this might not occur in the future anymore.

All in all, this issue is obsolete and doesn't need any fix on the code base, and gets therefore be closed. If the issue persists, please create a new issue, also providing the application used to reproduce the issue. It should go without saying, that if the application version is not the latest version of the application, the issue will be closed as obsolete again.

**Closed by onepiecefreak3** 2021-07-21 21:09 UTC

**Comment by onepiecefreak3** [comment] 2021-07-21 22:35
Release 2.1.3 now has automatic script detection.

**Comment by in1tiate** [comment] 2021-07-23 13:54
Oh, it was user error. Pff, figures. Thanks for looking at it anyway ❤️
